// Code generated by protoc-gen-go.
// source: sunteng_rtb.proto
// DO NOT EDIT!

package main

import (
	math "math"

	"github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

var E_A = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         101,
	Name:          "com.google.openrtb.A",
	Tag:           "varint,101,opt",
}

var E_B = &proto.ExtensionDesc{
	ExtendedType:  (*BidRequest)(nil),
	ExtensionType: (*bool)(nil),
	Field:         102,
	Name:          "com.google.openrtb.B",
	Tag:           "varint,102,opt",
}

func init() {
	proto.RegisterExtension(E_A)
	proto.RegisterExtension(E_B)
}
